function rotCell = cropCellRotate(cropCell)
%%cropCellRotate Parses the cropCell cell array, rotates the images and
%%coordiantes based on the centroids of the spbs and returns them in the
%rotCell cell array.
%
%   input :
%       cropCell : Cell array of rfp and gfp images and SPB centroids
%       generated by the cropPairs function.
%
%   output :
%       rotCell : Cell array of rotated rfp and gfp images and the rotated
%       SPB coordinates. Note, the coordinates ordered Y, X, Z.
%
%   Written by Josh Lawrimore, 1/23/2019
%% Preallocate the cell array
rotCell = cell(size(cropCell));
%% Loop through the cropCell array row-wise
for n = 1:size(cropCell, 1)
    %% Calculate angle of rotation based on SPB coordinates
    spbSub = cropCell{n,4}(1:2) - cropCell{n,3}(1:2);
    theta = rad2deg(atan2(spbSub(2), spbSub(1)));
    %% rotate the images
    rotCell{n,1} = imrotate(cropCell{n,1}, theta);
    rotCell{n,2} = imrotate(cropCell{n,2}, theta);
    %% rotate the centroids of the SPB coordinates
    R = [cosd(theta) -sind(theta); sind(theta) cosd(theta)];
    for i= 3:4
        coords = fliplr(cropCell{n,i}(1:2))';
        imCenter = (size(cropCell{n,1})/2)';
        rotImCenter = (size(rotCell{n,1})/2)';
        rotCell{n,i} = [R*(coords-imCenter(1:2))+rotImCenter(1:2);...
            cropCell{n,i}(3)]';
    end
end
    