function [mu, rsquare] = noisedGaussFit(gfpArray)
%CREATEFIT(GFPARRAY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: gfpArray
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jan-2019 13:15:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], gfpArray );

% Set up fittype and options.
ft = fittype( 'z + a*exp((-1/2)*((x-mu)/sigma)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0, 1, 0, 0];
opts.StartPoint = [max(gfpArray), length(gfpArray)/2, 1, 0];
opts.Upper = [max(gfpArray)*3 length(gfpArray) length(gfpArray) max(gfpArray)];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
rsquare = gof.rsquare;
coeffs = coeffvalues(fitresult);
mu = coeffs(2);
% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'gfpArray', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel gfpArray
% grid on


