function visualizeRotations(rotCell)
%%visualizeRotations Plots the rotated coordinates of the SPBs in the
%%rotCell cell array over the rotated images of the SPBs.
%
%   input :
%       rotCell : Cell array containing the rotated images and coordinates
%       generated by the cropCellRotate function.
%
%   output :
%       Scatter plot of the SPB centroids over the rotated image. Press
%       any button to advance the for loop to the next image. Images are
%       in-focus-planes of the each SPB.

%% Loop over rotCell array row-wise
for n = 1:size(rotCell,1)
    h = figure('WindowState', 'maximized');
    rfp = rotCell{n,1};
    rfpNan(rfp == 0) = nan;
    modeRfp = mode(rfpNan(:));
    rfp(rfp == 0) = modeRfp;
    subplot(1,2,1);
    imshow(rfp(:,:, round(rotCell{n,3}(3))), []);
    hold on;
    scatter(rotCell{n,3}(2), rotCell{n,3}(1));
    hold off;
    subplot(1,2,2);
    imshow(rfp(:,:, round(rotCell{n,4}(3))), []);
    hold on;
    scatter(rotCell{n,4}(2), rotCell{n,4}(1));
    hold off;
    waitforbuttonpress;
    close(h);
end
    
    
    
    